title: Classification
type: community
group: Project Type
image: /static/templates/classification.jpg
details: <h1>Classify the image</h1>
config: |
  <View>
    <Image name="image" value="$image"/>
    <Choices name="choice" toName="image">
      <Choice value="Purgue" />
      <Choice value="Screw" />
    </Choices>
  </View>

