title: Presence/Absence
type: community
group: Project Type
order: 3
image: /static/templates/presence_absence.jpg
details: <h1>Draw a bounding box around the object</h1>
config: |
  <View>
    <Image name="image" value="$image"/>
    <RectangleLabels name="label" toName="image">
      <Label value="Filament" background="green"/>
      <Label value="Head" background="blue"/>
    </RectangleLabels>
  </View>
