title: Detect and measure
type: community
group: Project Type
order: 1
image: /static/templates/detect_measure.jpg
details: <h1>Draw a polygon around object</h1>
config: |
  <View>

    <Header value="Select label and click the image to start"/>
    <Image name="image" value="$image" zoom="true"/>

    <PolygonLabels name="label" toName="image"
                   strokeWidth="3" pointSize="small"
                   opacity="0.9">
      <Label value="Code" background="red"/>
      <Label value="Tag" background="blue"/>
    </PolygonLabels>

  </View>
